### ISSUE TITLE
Homebrew users who get error regarding xcb-shm

### ISSUE THREAD

**Issue by naturalethic** [selaux/node-sprite-generator#23]
The fix is to add this to your bash profile / environment:

export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig

(Perhaps put this somewhere in the readme)

https://github.com/Homebrew/homebrew/issues/14123

**Comment by nucleardreamer** [comment]
For anyone new following this problem from installing xquartz, and then cairo from homebrew make sure to add the `PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig` line to either `~/.bash_profile` or `~/.bashrc` depending on what you have setup.
