### ISSUE TITLE
sprite image is not generating

### ISSUE THREAD

**Issue by sch00lb0y** [selaux/node-sprite-generator#51]

**Comment by selaux** [comment]
Some more information please 😉

**Comment by sch00lb0y** [comment]
```
var nsg = require('node-sprite-generator');

nsg({
    src: [
        '../images/*.png'
    ],
    spritePath: '../sprite.png',
    stylesheetPath: '../sprite.css',
    stylesheet: 'css'
}, function (err) {
    console.log('Sprite generated!');
});

```
here is my script .the image folder nearly having 700 images .sprite.css is generating but sprite.png is not
@selaux

**Comment by selaux** [comment]
Is there any error? Did you try different compositors?

**Comment by sch00lb0y** [comment]
```
Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
    at Error (native)
```
i'm getting this error @selaux thanks for your support

**Comment by selaux** [comment]
Did you check how big the sprite will get, maybe it's getting too big for memory...

**Comment by sch00lb0y** [comment]
ohh no i didn't check that i'll try to make as two separate sprite and let you know Thanks!!
