### ISSUE TITLE
Pass input source and retrieve output source as buffers

### ISSUE THREAD

**Issue by tresdin** [selaux/node-sprite-generator#61]
How can I pass list of input files into node-sprite-generator in buffer format and retrieve the output data as buffer also?

**Comment by selaux** [comment]
This is planned for the next release and should actually work in current master. Just use `fs.readFile` and pass the result in to `node-sprite-generator`.

**Comment by selaux** [comment]
Well I was not totally correct you have to pass objects like: `{ path: 'foobar.jpg', data: buffer }` as it needs to determine the sprite names from the path.

**Comment by tresdin** [comment]
I got it. Thanks.

**Comment by tresdin** [comment]
Oh sorry, but how can I pass multiple bufferred files into `node-sprite-generator`? Will I need to use an array of objects like the above?

**Comment by selaux** [comment]
Yes.
